<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_31</name>
   <tag></tag>
   <elementGuidId>d4a8b26a-514e-4da1-833b-8b1607b60e29</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/my-app[1]/app-history-log[1]/div[@class=&quot;container-fluid&quot;]/div[2]/div[@class=&quot;row&quot;]/div[@class=&quot;container centurygothic-font&quot;]/div[@class=&quot;row w3-margin-top w3-margin-bottom&quot;]/div[@class=&quot;col-xs-12 col-sm-6&quot;]/div[@class=&quot;form&quot;]/div[@class=&quot;col-xs-5&quot;]/my-date-picker[1]/div[@class=&quot;mydp&quot;]/div[@class=&quot;selector selectorarrow selectorarrowleft&quot;]/table[@class=&quot;caltable&quot;]/tbody[1]/tr[5]/td[@class=&quot;daycell currmonth tablesingleday&quot;]/div[@class=&quot;datevalue currmonth&quot;]/span[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>31</value>
   </webElementProperties>
</WebElementEntity>
