<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_fortest</name>
   <tag></tag>
   <elementGuidId>db66d562-24b6-4caf-97d4-9352445c80f3</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/my-app[1]/app-user-management[1]/div[@class=&quot;container-fluid&quot;]/div[2]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table centurygothic-font&quot;]/tbody[1]/tr[2]/td[@class=&quot;w3-text-gray&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>fortest</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w3-text-gray</value>
   </webElementProperties>
</WebElementEntity>
