<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_selection ng-untouched n</name>
   <tag></tag>
   <elementGuidId>028d0f15-b2ec-417c-8a47-8c2ee2ff003e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selection ng-untouched ng-valid invaliddate ng-dirty</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ngtype</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Date input field</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/my-app[1]/app-history-log[1]/div[@class=&quot;container-fluid&quot;]/div[2]/div[@class=&quot;row&quot;]/div[@class=&quot;container centurygothic-font&quot;]/div[@class=&quot;row w3-margin-top w3-margin-bottom&quot;]/div[@class=&quot;col-xs-12 col-sm-6&quot;]/div[@class=&quot;form&quot;]/div[@class=&quot;col-xs-5&quot;]/my-date-picker[1]/div[@class=&quot;mydp&quot;]/div[@class=&quot;selectiongroup&quot;]/input[@class=&quot;selection ng-untouched ng-valid invaliddate ng-dirty&quot;]</value>
   </webElementProperties>
</WebElementEntity>
