<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Creme</name>
   <tag></tag>
   <elementGuidId>b3eeb5e1-6298-4a14-950a-1f1ade3b5234</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[count(. | //*[text() = 'Creme']) = count(//*[text() = 'Creme'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w3-text-gray</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Creme</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/my-app[1]/app-user-management[1]/div[@class=&quot;container-fluid&quot;]/div[2]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table centurygothic-font&quot;]/tbody[1]/tr[4]/td[@class=&quot;w3-text-gray&quot;]</value>
   </webElementProperties>
</WebElementEntity>
