<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_w3-center</name>
   <tag></tag>
   <elementGuidId>b7a42421-f0f9-4ec6-875d-fcebfc639f1b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w3-center</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/img/reset-password.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>160px</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/my-app[1]/app-edit-profile[1]/div[@class=&quot;popup-zone&quot;]/div[@class=&quot;reset-password-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-5 col-sm-5 col-md-5 col-lg-5 w3-padding-32&quot;]/img[@class=&quot;w3-center&quot;]</value>
   </webElementProperties>
</WebElementEntity>
