<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Capacity</name>
   <tag></tag>
   <elementGuidId>9a3e39d6-3abd-45b6-a245-149d7ab4cf73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[count(. | //*[contains(.,'Capacity')]) = count(//*[contains(.,'Capacity')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Capacity</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/my-app[1]/app-predicted-results[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row centurygothic-font&quot;]/div[@class=&quot;col-xs-12 col-sm-4 col-md-4 col-lg-3&quot;]/ngx-treeview[1]/div[2]/div[@class=&quot;treeview-container&quot;]/ngx-treeview-item[1]/div[@class=&quot;treeview-item&quot;]/div[2]/ngx-treeview-item[1]/div[@class=&quot;treeview-item&quot;]/div[@class=&quot;form-check&quot;]/label[@class=&quot;form-check-label&quot;]</value>
   </webElementProperties>
</WebElementEntity>
