<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_..</name>
   <tag></tag>
   <elementGuidId>70809bfc-eb38-4e4e-80f0-287b6c26668d</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/my-app[1]/app-history-log[1]/div[@class=&quot;container-fluid&quot;]/div[2]/div[@class=&quot;row&quot;]/div[@class=&quot;container centurygothic-font&quot;]/div[@class=&quot;row w3-margin-top w3-margin-bottom&quot;]/div[@class=&quot;col-xs-12 col-sm-6&quot;]/div[@class=&quot;form&quot;]/div[@class=&quot;col-xs-5&quot;]/my-date-picker[1]/div[@class=&quot;mydp&quot;]/div[@class=&quot;selector selectorarrow selectorarrowleft&quot;]/table[@class=&quot;header&quot;]/tbody[1]/tr[1]/td[1]/div[1]/div[@class=&quot;headermonthtxt&quot;]/button[@class=&quot;headerlabelbtn monthlabel&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ต.ค.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>headerlabelbtn monthlabel</value>
   </webElementProperties>
</WebElementEntity>
